---
kind: pipeline
type: docker
name: default

trigger:
  event:
  - tag

steps:
- name: test
  image: mingc/android-build-box:1.12.0
  mem_limit: 800000000
  environment:
    GRADLE_HOME: /root/.gradle
  volumes:
  - name: build-cache
    path: /root/.gradle/caches
  - name: build-result
    path: /drone/src/app/build
  - name: build-deps-jar
    path: /drone/src/app/libs
  - name: build-deps-jni
    path: /drone/src/app/jniLibs
  commands:
  - cd /drone/src && ./gradlew --build-cache build assembleAndroidTest -Papk_version=${DRONE_TAG}
  - test -f /drone/src/app/build/outputs/apk/androidTest/debug/app-debug-androidTest.apk
  - test -f /drone/src/app/build/outputs/apk/debug/app-debug.apk
- name: publish
  image: plugins/github-release
  volumes:
  - name: build-result
    path: /tmp/build
  settings:
    api_key:
      from_secret: release-token
    files:
    - /tmp/build/outputs/apk/androidTest/debug/app-debug-androidTest.apk
    - /tmp/build/outputs/apk/debug/app-debug.apk
    title: 0.0.1

volumes:
- name: build-result
  temp: {}
- name: build-cache
  host:
    path: /root/AndroidTestRunner/build-cache
- name: build-deps-jar
  host:
    path: /root/AndroidTestRunner/app/libs
- name: build-deps-jni
  host:
    path: /root/AndroidTestRunner/app/jniLibs
