---
kind: pipeline
type: docker
name: default

trigger:
  event:
  - tag

steps:
- name: test
  image: mingc/android-build-box:1.12.0
  volumes:
  - name: build-result
    path: /drone/src/app/build
  commands:
  - cd /drone/src && ./gradlew build assembleAndroidTest
  - test -f /drone/src/app/build/outputs/apk/androidTest/debug/app-debug-androidTest.apk
  - test -f /drone/src/app/build/outputs/apk/debug/app-debug.apk
- name: publish
  image: plugins/github-release
  volumes:
  - name: build-result
    path: /tmp/build
  settings:
    api_key:
      from_secret: release-token
    files:
    - /tmp/build/outputs/apk/androidTest/debug/app-debug-androidTest.apk
    - /tmp/build/outputs/apk/debug/app-debug.apk
    title: 0.0.1

volumes:
- name: build-result
  temp: {}